repos:
  - repo: local
    # Defining as local hooks to permit reuse of already-installed dev
    # dependencies
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        require_serial: true
        types_or: [cython, pyi, python]
        args: ["--filter-files", "--check-only"]
      - id: black
        name: black
        entry: poetry run black
        language: system
        require_serial: true
        args: ["--check"]
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        require_serial: true
        types_or: [python, pyi]
        pass_filenames: false
        args:
          - --namespace-packages
          - --package
          - "glob_tries"
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        require_serial: true
        types: [python]
      - id: bandit
        name: bandit
        entry: poetry run bandit -c pyproject.toml
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml

